#Usa la imagen oficial de Node.js
FROM node:20

# Establece el directorio de trabajo
WORKDIR /api

# Copia los archivos necesarios
COPY ./api/package*.json ./
COPY ./api/ .

# Instala las dependencias
RUN npm install

# Expone el puerto en el que la API estará escuchando
EXPOSE 4000

# Comando para ejecutar la API
CMD ["npm", "start"]